name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Changesets Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Restore NPM cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Show NPM cache contents
        run: |
          echo "Cached npm modules (if any):"
          du -sh ~/.npm || echo "No .npm directory found"
          ls -la ~/.npm/_cacache || echo "No .npm/_cacache found"

      - name: Install dependencies
        run: npm ci --verbose

      - name: Build package
        run: npm run build

      - name: Publish with Changesets
        run: npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
